### ISSUE TITLE
Symbolic linking doesn't happen

### ISSUE THREAD

**Issue by andrewraj** [apowers313/piwallcontrol#1]
ln -s . piwallcontrol ~/bin

Throws back error the folder /home/pi/bin does not exists. If '~bin' is changed to just '/bin', it says 'file exists'.

**Comment by apowers313** [comment]
That's all controlled by the unix shell and has nothing to do with this application. See also: https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html

Looks like you might have been using `~bin` which would resolve to `/home/bin`. You should be using `~/bin` which would resolve to `/home/<your username>/bin`.
